<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Web\Module'                        => __DIR__ . '/Module.php',
    'Web\Controller\AdminController' => __DIR__ . '/src/Web/Controller/AdminController.php',
    'WebTest\Framework\TestCase'        => __DIR__ . '/tests/Web/Framework/TestCase.php',
    'WebTest\SampleTest'                => __DIR__ . '/tests/Web/SampleTest.php',
);
