<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Message\Module'                        => __DIR__ . '/Module.php',
    'Message\Controller\ProcessingController' => __DIR__ . '/src/Message/Controller/ProcessingController.php',
    'MessageTest\Framework\TestCase'        => __DIR__ . '/tests/Message/Framework/TestCase.php',
    'MessageTest\SampleTest'                => __DIR__ . '/tests/Message/SampleTest.php',
);
