<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CMS\Module'                        => __DIR__ . '/Module.php',
    'CMS\Controller\IndexController' => __DIR__ . '/src/CMS/Controller/IndexController.php',
    'CMSTest\Framework\TestCase'        => __DIR__ . '/tests/CMS/Framework/TestCase.php',
    'CMSTest\SampleTest'                => __DIR__ . '/tests/CMS/SampleTest.php',
);
