<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Keywords\Module'                        => __DIR__ . '/Module.php',
    'Keywords\Controller\IndexController' => __DIR__ . '/src/Keywords/Controller/IndexController.php',
    'KeywordsTest\Framework\TestCase'        => __DIR__ . '/tests/Keywords/Framework/TestCase.php',
    'KeywordsTest\SampleTest'                => __DIR__ . '/tests/Keywords/SampleTest.php',
);
