<?php 

?>

<div style="float: left">
    <ul>
        <li><a id='addUser' href="#">添加用户</a></li>
        
    </ul>
</div>
<table class="table"> 
    <tr>
        <th>全名</th>
        <th>用户号</th>
        <th>密码</th>
       
        <th>角色</th>
        <th></th>
        <th></th>
    </tr>
    <?php $i=0;foreach ($this->userPaginator as $userEntity) : $i++;?>
     <tr>
        <td style="display: none" id="id<?php echo $i;?>" ><?=$userEntity->getId()?></td>
        <td><?=$userEntity->getFullName();?></td>
        <td><?=$userEntity->getUsername();?></td>
        <td><?=$userEntity->getPassword();?></td>
        <td><?=null!==$userEntity->getRole()?$userEntity->getRole()->getRoleName():'';?></td>
        <td><a onClick="edit(<?php echo $i;?>)"  href="#">编辑</a></td>
        <td><a onClick="delect(<?php echo $i;?>)" href="#">删除</a></td>
    </tr>
    <?php endforeach;?>
</table>

<?=$this->paginationcontrol($this->userPaginator,'all','user\pagination',['a'=>3]);?>






<script>
var addLayerIndex;
var editLayerIndex;

function addSubmit(){
		$.ajax({
			url:'<?php echo $this->url('User',['controller'=>'list','action'=>'addUser'])?>',
			type:'POST',
			data: $('#form').serialize(),
			success : function(data){
				     var result = JSON.parse(data);
				 	if(result.status=='fail'){
						layer.msg(result.msg);
					
						}
					else if(result.status=='success'){
						layer.msg(result.msg);
						layer.close(addLayerIndex);
						location.reload();
						}
					
					
					
				}
			});
		}
function editSubmit(){
	$.ajax({
		url:'<?php echo $this->url('User',['controller'=>'list','action'=>'editUser'])?>',
		type:'POST',
		data: $('#form').serialize(),
		success : function(data){
			    var result = JSON.parse(data);
			 	if(result.status=='fail'){
					layer.msg(result.msg);
				
					}
				else if(result.status=='success'){
					layer.msg(result.msg);
					layer.close(editLayerIndex);
					location.reload();
					}
				
				
				
			}
		});
	}
function delect(i){
	var id = $('#id'+i).text();
	 layer.open({
	  //      shadeClose: true, //点击遮罩关闭
	        content: '确定删除吗?',
	       	yes : function (index){
				$.ajax({
					url:'<?php echo $this->url('User',['controller'=>'list','action'=>'delectUser'])?>?userId='+id,
					success : function(data){
						
						var result = JSON.parse(data);
						if(result.status=='fail'){
							layer.msg(result.msg);
							layer.close(index);
							}
						else if(result.status=='success'){
							layer.msg(result.msg);
							layer.close(index);
							location.reload();
							}
						}
					});
		       	}
	    });
}

function edit(i){
	var id = $('#id'+i).text();

	$.ajax({
		url:'<?php echo $this->url('User',['controller'=>'list','action'=>'editUser'])?>?userId='+id,
		success : function(data){
			editLayerIndex =  layer.open({
			    	type:1,
			        area: ['600px', '360px'],
			  //      shadeClose: true, //点击遮罩关闭
			        content: data
			    });
			}
		});
	

}


$('#addUser').on('click', function(){

	$.ajax({
		url:'<?php echo $this->url('User',['controller'=>'list','action'=>'addUser'])?>',
		success : function(data){
			addLayerIndex =  layer.open({
			    	type:1,
			        area: ['600px', '360px'],
			  //      shadeClose: true, //点击遮罩关闭
			        content: data
			    });
			}
		});
		
	
});

</script>