<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Fans\Module'                        => __DIR__ . '/Module.php',
    'Fans\Controller\IndexController' => __DIR__ . '/src/Fans/Controller/IndexController.php',
    'FansTest\Framework\TestCase'        => __DIR__ . '/tests/Fans/Framework/TestCase.php',
    'FansTest\SampleTest'                => __DIR__ . '/tests/Fans/SampleTest.php',
);
