<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Api\Module'                        => __DIR__ . '/Module.php',
    'Api\Controller\RestController' => __DIR__ . '/src/Api/Controller/RestController.php',
    'ApiTest\Framework\TestCase'        => __DIR__ . '/tests/Api/Framework/TestCase.php',
    'ApiTest\SampleTest'                => __DIR__ . '/tests/Api/SampleTest.php',
);
